#define WINVER 0x0601
#define _WIN32_WINNT 0x0601
#include <winsock2.h>
#include <windows.h>
#include <ws2tcpip.h>
#include <commctrl.h>
#include <mmsystem.h>
#include <stdio.h>
#include <algorithm>
#include <gdiplus.h>
using namespace Gdiplus;

HWND W,ipbox,portbox,edgebox,fpsbox,qualitybox,modebox,status,captureBtn,sensbox,stretchbox;
SOCKET sock=INVALID_SOCKET; CRITICAL_SECTION cs; Image* img=0; int iw=1,ih=1;
bool drag=false,inputOnly=false,mouseCaptured=false,stretchScreen=false,fullScreen=false; WINDOWPLACEMENT oldPlace={sizeof(WINDOWPLACEMENT)}; LONG oldStyle=0; POINT downp; ULONG_PTR gdip;
HDC backDC=0; HBITMAP backBmp=0; HGDIOBJ backOld=0; int backW=0,backH=0;

void sendline(const char*s){if(sock!=INVALID_SOCKET)send(sock,s,(int)strlen(s),0);}
int norm(int v,int n){if(n<=1)return 0;if(v<0)v=0;if(v>n-1)v=n-1;return v*65535/(n-1);}
RECT view(){RECT r;GetClientRect(W,&r);if(!fullScreen){r.top=62;r.bottom-=26;}return r;}
RECT imageRect(){RECT r=view(),d=r;if(stretchScreen)return r;int w=iw,h=ih;if(w<=0||h<=0)return d;double s=std::min((double)(r.right-r.left)/w,(double)(r.bottom-r.top)/h);int dw=(int)(w*s),dh=(int)(h*s);d.left=r.left+(r.right-r.left-dw)/2;d.top=r.top+(r.bottom-r.top-dh)/2;d.right=d.left+dw;d.bottom=d.top+dh;return d;}
bool mapScreenPoint(POINT p,int&nx,int&ny){RECT d=imageRect();if(p.x<d.left||p.x>=d.right||p.y<d.top||p.y>=d.bottom)return false;nx=norm(p.x-d.left,d.right-d.left);ny=norm(p.y-d.top,d.bottom-d.top);return true;}

void ensureBackBuffer(HDC dc,int w,int h){if(backDC&&w==backW&&h==backH)return;if(backDC){SelectObject(backDC,backOld);DeleteObject(backBmp);DeleteDC(backDC);}backDC=CreateCompatibleDC(dc);backBmp=CreateCompatibleBitmap(dc,w,h);backOld=SelectObject(backDC,backBmp);backW=w;backH=h;}
void freeBackBuffer(){if(backDC){SelectObject(backDC,backOld);DeleteObject(backBmp);DeleteDC(backDC);backDC=0;backBmp=0;backOld=0;}}

DWORD WINAPI rx(LPVOID){for(;;){int h[4],got=0;char*p=(char*)h;while(got<16){int n=recv(sock,p+got,16-got,0);if(n<=0)goto end;got+=n;}for(int i=0;i<4;i++)h[i]=ntohl(h[i]);if(h[0]!=0x4C525631||h[3]<=0||h[3]>5000000)goto end;BYTE*b=new BYTE[h[3]];got=0;while(got<h[3]){int n=recv(sock,(char*)b+got,h[3]-got,0);if(n<=0){delete[]b;goto end;}got+=n;}HGLOBAL hg=GlobalAlloc(GMEM_MOVEABLE,h[3]);void*q=GlobalLock(hg);memcpy(q,b,h[3]);GlobalUnlock(hg);delete[]b;IStream*stm=0;CreateStreamOnHGlobal(hg,TRUE,&stm);Image*ni=Image::FromStream(stm);if(ni&&ni->GetLastStatus()==Ok){EnterCriticalSection(&cs);delete img;img=ni;iw=h[1];ih=h[2];LeaveCriticalSection(&cs);InvalidateRect(W,0,FALSE);}else delete ni;stm->Release();}end:SetWindowText(status,"Disconnected");closesocket(sock);sock=INVALID_SOCKET;return 0;}

double mouseGain(){int i=(int)SendMessage(sensbox,CB_GETCURSEL,0,0);const double g[]={0.75,1.0,1.5,2.0,3.0};return (i>=0&&i<5)?g[i]:2.0;}
void lockMouseToWindow(){RECT r;GetClientRect(W,&r);POINT a={r.left,r.top},b={r.right,r.bottom};ClientToScreen(W,&a);ClientToScreen(W,&b);RECT clip={a.x+2,a.y+2,b.x-2,b.y-2};ClipCursor(&clip);POINT c={(clip.left+clip.right)/2,(clip.top+clip.bottom)/2};SetCursorPos(c.x,c.y);}
void setMouseCapture(bool on){if(!inputOnly||sock==INVALID_SOCKET)on=false;if(on==mouseCaptured)return;mouseCaptured=on;if(on){SetForegroundWindow(W);SetFocus(W);SetCapture(W);lockMouseToWindow();while(ShowCursor(FALSE)>=0){}sendline("CURSOR SHOW\n");SetWindowText(captureBtn,"Release Mouse (Ctrl+Alt)");SetWindowText(status,"Input Only - mouse locked to Android; Ctrl+Alt releases");}else{ClipCursor(NULL);ReleaseCapture();while(ShowCursor(TRUE)<0){}sendline("CURSOR HIDE\n");SetWindowText(captureBtn,"Capture Mouse");if(inputOnly&&sock!=INVALID_SOCKET)SetWindowText(status,"Input Only - click Capture Mouse to control Android");}}

BOOL CALLBACK showChild(HWND h,LPARAM show){ShowWindow(h,show?SW_SHOW:SW_HIDE);return TRUE;}
void toggleFullScreen(bool on){if(on==fullScreen)return;if(on){oldStyle=GetWindowLong(W,GWL_STYLE);GetWindowPlacement(W,&oldPlace);MONITORINFO mi={sizeof(mi)};GetMonitorInfo(MonitorFromWindow(W,MONITOR_DEFAULTTONEAREST),&mi);fullScreen=true;EnumChildWindows(W,showChild,FALSE);SetWindowLong(W,GWL_STYLE,oldStyle&~(WS_CAPTION|WS_THICKFRAME|WS_MINIMIZEBOX|WS_MAXIMIZEBOX|WS_SYSMENU));SetWindowPos(W,HWND_TOP,mi.rcMonitor.left,mi.rcMonitor.top,mi.rcMonitor.right-mi.rcMonitor.left,mi.rcMonitor.bottom-mi.rcMonitor.top,SWP_FRAMECHANGED);}
else{fullScreen=false;SetWindowLong(W,GWL_STYLE,oldStyle);SetWindowPlacement(W,&oldPlace);SetWindowPos(W,0,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOZORDER|SWP_FRAMECHANGED);EnumChildWindows(W,showChild,TRUE);if(inputOnly)ShowWindow(captureBtn,SW_SHOW);else ShowWindow(captureBtn,SW_HIDE);}InvalidateRect(W,0,FALSE);}
void connectNow(){char ip[64],po[16],e[16],f[16],qu[16];GetWindowText(ipbox,ip,64);GetWindowText(portbox,po,16);GetWindowText(edgebox,e,16);GetWindowText(fpsbox,f,16);GetWindowText(qualitybox,qu,16);setMouseCapture(false);inputOnly=(SendMessage(modebox,CB_GETCURSEL,0,0)==1);sock=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in a={0};a.sin_family=AF_INET;int port=atoi(po);if(port<1||port>65535)port=7878;a.sin_port=htons((u_short)port);a.sin_addr.s_addr=inet_addr(ip);if(connect(sock,(sockaddr*)&a,sizeof(a))!=0){SetWindowText(status,"Connect failed");closesocket(sock);sock=INVALID_SOCKET;return;}if(inputOnly){sendline("INPUTONLY\n");sendline("CURSOR HIDE\n");ShowWindow(captureBtn,SW_SHOW);SetWindowText(status,"Input Only - click Capture Mouse; keyboard is active");}else{ShowWindow(captureBtn,SW_HIDE);char q[64];sprintf(q,"VIDEO %s %s %s\n",e,f,qu);sendline(q);SetWindowText(status,"Screen + Control connected");CreateThread(0,0,rx,0,0,0);}SetTimer(W,1,16,0);SetFocus(W);}

void paintBuffered(HWND w){PAINTSTRUCT ps;HDC dc=BeginPaint(w,&ps);RECT client;GetClientRect(w,&client);ensureBackBuffer(dc,client.right,client.bottom);FillRect(backDC,&client,(HBRUSH)(COLOR_BTNFACE+1));RECT r=view();FillRect(backDC,&r,(HBRUSH)GetStockObject(BLACK_BRUSH));EnterCriticalSection(&cs);if(img&&!inputOnly){Graphics g(backDC);g.SetInterpolationMode(InterpolationModeBilinear);RECT d=imageRect();g.DrawImage(img,(INT)d.left,(INT)d.top,(INT)(d.right-d.left),(INT)(d.bottom-d.top));}LeaveCriticalSection(&cs);if(inputOnly){SetBkMode(backDC,TRANSPARENT);SetTextColor(backDC,RGB(235,235,235));RECT tr=r;tr.top+=30;DrawText(backDC,mouseCaptured?"INPUT ONLY - MOUSE CAPTURED\r\nLook at the Android screen.\r\nCtrl + Alt releases the mouse.":"INPUT ONLY\r\nLook at the Android screen.\r\nClick Capture Mouse to send mouse movement to Android.",-1,&tr,DT_CENTER|DT_TOP);}BitBlt(dc,0,0,client.right,client.bottom,backDC,0,0,SRCCOPY);EndPaint(w,&ps);}

void pollGamepad(){if(sock==INVALID_SOCKET)return;JOYINFOEX j={0};j.dwSize=sizeof(j);j.dwFlags=JOY_RETURNALL;static DWORD oldButtons=0;static bool init=false;if(joyGetPosEx(JOYSTICKID1,&j)!=JOYERR_NOERROR){init=false;return;}int dx=((int)j.dwXpos-32767)/4500,dy=((int)j.dwYpos-32767)/4500;if(abs(dx)>1||abs(dy)>1){char q[64];sprintf(q,"MOUSE %d %d\n",dx,dy);sendline(q);}if(!init){oldButtons=j.dwButtons;init=true;return;}DWORD pressed=j.dwButtons&~oldButtons;if(pressed&JOY_BUTTON1)sendline("CLICK\n");if(pressed&JOY_BUTTON2)sendline("GLOBAL BACK\n");if(pressed&JOY_BUTTON3)sendline("GLOBAL HOME\n");oldButtons=j.dwButtons;}

bool sendKeyboard(UINT m,WPARAM wp){if((m==WM_KEYDOWN||m==WM_SYSKEYDOWN)&&wp=='F'&&(GetAsyncKeyState(VK_MENU)&0x8000)){toggleFullScreen(!fullScreen);return true;}if((m==WM_KEYDOWN||m==WM_SYSKEYDOWN)&&wp==VK_ESCAPE&&fullScreen){toggleFullScreen(false);return true;}if(sock==INVALID_SOCKET)return false;if((GetAsyncKeyState(VK_CONTROL)&0x8000)&&(GetAsyncKeyState(VK_MENU)&0x8000)){if(mouseCaptured)setMouseCapture(false);return true;}if(m==WM_CHAR){char q[64];if(wp==8)sendline("KEY BACKSPACE\n");else if(wp==13)sendline("KEY ENTER\n");else if(wp==32)sendline("KEY SPACE\n");else if(wp>=33&&wp<127){sprintf(q,"TEXT 0 0 %c\n",(char)wp);sendline(q);}return true;}if(m==WM_KEYDOWN){if(wp==VK_LEFT)sendline("KEY LEFT\n");else if(wp==VK_RIGHT)sendline("KEY RIGHT\n");else if(wp==VK_UP)sendline("KEY UP\n");else if(wp==VK_DOWN)sendline("KEY DOWN\n");else if(wp==VK_ESCAPE)sendline("GLOBAL BACK\n");else return false;return true;}return false;}

LRESULT CALLBACK proc(HWND w,UINT m,WPARAM wp,LPARAM lp){
 if(m==WM_CREATE){CreateWindow("STATIC","IP",WS_CHILD|WS_VISIBLE,8,10,20,20,w,0,0,0);ipbox=CreateWindow("EDIT","192.168.1.100",WS_CHILD|WS_VISIBLE|WS_BORDER,30,7,135,22,w,0,0,0);CreateWindow("STATIC","Port",WS_CHILD|WS_VISIBLE,171,10,28,18,w,0,0,0);portbox=CreateWindow("EDIT","7878",WS_CHILD|WS_VISIBLE|WS_BORDER,201,7,48,22,w,0,0,0);modebox=CreateWindow("COMBOBOX","",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,260,7,150,120,w,(HMENU)4,0,0);SendMessage(modebox,CB_ADDSTRING,0,(LPARAM)"Screen + Control");SendMessage(modebox,CB_ADDSTRING,0,(LPARAM)"Input Only");SendMessage(modebox,CB_SETCURSEL,0,0);edgebox=CreateWindow("COMBOBOX","",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,420,7,80,120,w,(HMENU)2,0,0);const char*rs[]={"480","720","960","1200"};for(int i=0;i<4;i++)SendMessage(edgebox,CB_ADDSTRING,0,(LPARAM)rs[i]);SendMessage(edgebox,CB_SETCURSEL,1,0);fpsbox=CreateWindow("COMBOBOX","",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,424,7,52,140,w,(HMENU)3,0,0);const char*fs[]={"7","15","24","60"};for(int i=0;i<4;i++)SendMessage(fpsbox,CB_ADDSTRING,0,(LPARAM)fs[i]);SendMessage(fpsbox,CB_SETCURSEL,1,0);CreateWindow("STATIC","JPEG",WS_CHILD|WS_VISIBLE,580,10,38,18,w,0,0,0);qualitybox=CreateWindow("COMBOBOX","",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,620,7,55,120,w,(HMENU)8,0,0);const char*qs[]={"35","50","65","80"};for(int i=0;i<4;i++)SendMessage(qualitybox,CB_ADDSTRING,0,(LPARAM)qs[i]);SendMessage(qualitybox,CB_SETCURSEL,1,0);CreateWindow("BUTTON","Connect",WS_CHILD|WS_VISIBLE,685,7,75,23,w,(HMENU)1,0,0);captureBtn=CreateWindow("BUTTON","Capture Mouse",WS_CHILD,654,7,145,23,w,(HMENU)5,0,0);stretchbox=CreateWindow("BUTTON","Stretch",WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,805,9,68,20,w,(HMENU)6,0,0);CreateWindow("STATIC","Mouse",WS_CHILD|WS_VISIBLE,878,10,38,18,w,0,0,0);sensbox=CreateWindow("COMBOBOX","",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,918,7,62,120,w,(HMENU)7,0,0);const char*gs[]={"0.75x","1x","1.5x","2x","3x"};for(int i=0;i<5;i++)SendMessage(sensbox,CB_ADDSTRING,0,(LPARAM)gs[i]);SendMessage(sensbox,CB_SETCURSEL,3,0);status=CreateWindow("STATIC","Ready - Alt+F fullscreen / Esc exit fullscreen",WS_CHILD|WS_VISIBLE,8,37,970,18,w,0,0,0);return 0;}
 if(m==WM_COMMAND&&LOWORD(wp)==1){connectNow();return 0;}if(m==WM_COMMAND&&LOWORD(wp)==5){setMouseCapture(!mouseCaptured);InvalidateRect(w,0,FALSE);return 0;}if(m==WM_COMMAND&&LOWORD(wp)==6){stretchScreen=(SendMessage(stretchbox,BM_GETCHECK,0,0)==BST_CHECKED);InvalidateRect(w,0,FALSE);return 0;}
 if(m==WM_ERASEBKGND)return 1;if(m==WM_PAINT){paintBuffered(w);return 0;}if(m==WM_SIZE){freeBackBuffer();InvalidateRect(w,0,FALSE);return 0;}
 if(m==WM_INPUT&&mouseCaptured&&inputOnly&&sock!=INVALID_SOCKET){UINT sz=0;GetRawInputData((HRAWINPUT)lp,RID_INPUT,0,&sz,sizeof(RAWINPUTHEADER));BYTE buf[128];if(sz<=sizeof(buf)&&GetRawInputData((HRAWINPUT)lp,RID_INPUT,buf,&sz,sizeof(RAWINPUTHEADER))==sz){RAWINPUT*ri=(RAWINPUT*)buf;if(ri->header.dwType==RIM_TYPEMOUSE){LONG dx=ri->data.mouse.lLastX,dy=ri->data.mouse.lLastY;if(dx||dy){double g=mouseGain();LONG sx=(LONG)(dx*g),sy=(LONG)(dy*g);if(sx==0&&dx)sx=dx>0?1:-1;if(sy==0&&dy)sy=dy>0?1:-1;char q[64];sprintf(q,"MOUSE %ld %ld\n",sx,sy);sendline(q);}}}return 0;}
 if((m==WM_LBUTTONDOWN||m==WM_LBUTTONUP)&&sock!=INVALID_SOCKET){POINT p={(short)LOWORD(lp),(short)HIWORD(lp)};if(inputOnly){if(mouseCaptured&&m==WM_LBUTTONUP)sendline("CLICK\n");return 0;}if(m==WM_LBUTTONDOWN){int x,y;if(!mapScreenPoint(p,x,y))return 0;drag=true;downp=p;SetCapture(w);}else if(drag){ReleaseCapture();drag=false;int x1,y1,x2,y2;if(!mapScreenPoint(downp,x1,y1)||!mapScreenPoint(p,x2,y2))return 0;char q[128];int dx=abs(p.x-downp.x),dy=abs(p.y-downp.y);if(dx+dy<8)sprintf(q,"TAP %d %d\n",x2,y2);else sprintf(q,"SWIPE %d %d %d %d 180\n",x1,y1,x2,y2);sendline(q);}return 0;}
 if(m==WM_MOUSEWHEEL&&sock!=INVALID_SOCKET&&inputOnly&&mouseCaptured){short z=GET_WHEEL_DELTA_WPARAM(wp);sendline(z>0?"SCROLL -1\n":"SCROLL 1\n");return 0;}
 if(m==WM_TIMER){pollGamepad();if(mouseCaptured){if(GetForegroundWindow()!=W){SetForegroundWindow(W);SetFocus(W);}lockMouseToWindow();}return 0;}if(m==WM_DESTROY){setMouseCapture(false);KillTimer(w,1);if(sock!=INVALID_SOCKET)closesocket(sock);freeBackBuffer();PostQuitMessage(0);return 0;}return DefWindowProc(w,m,wp,lp);
}

int WINAPI WinMain(HINSTANCE h,HINSTANCE,LPSTR,int){WSADATA wd;WSAStartup(MAKEWORD(2,2),&wd);GdiplusStartupInput gi;GdiplusStartup(&gdip,&gi,0);InitializeCriticalSection(&cs);RAWINPUTDEVICE rid={0x01,0x02,0,W};WNDCLASS wc={0};wc.style=CS_OWNDC;wc.lpfnWndProc=proc;wc.hInstance=h;wc.lpszClassName="LANRemote";wc.hCursor=LoadCursor(0,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_BTNFACE+1);RegisterClass(&wc);W=CreateWindow("LANRemote","LAN Remote v0.6 - Android over Wi-Fi",WS_OVERLAPPEDWINDOW|WS_VISIBLE,60,50,1020,650,0,0,h,0);rid.hwndTarget=W;RegisterRawInputDevices(&rid,1,sizeof(rid));MSG msg;while(GetMessage(&msg,0,0,0)){if((msg.message==WM_KEYDOWN||msg.message==WM_SYSKEYDOWN||msg.message==WM_CHAR)&&sendKeyboard(msg.message,msg.wParam))continue;TranslateMessage(&msg);DispatchMessage(&msg);}DeleteCriticalSection(&cs);GdiplusShutdown(gdip);WSACleanup();return 0;}
