package cl.will.lanremote;
import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import android.view.*;import java.io.*;import java.nio.*;
public class FrameStreamer {
 public interface Sink { void frame(byte[] jpg,int w,int h); }
 private final Context c; private final MediaProjection p; private final Sink sink; private HandlerThread t; private Handler h; private ImageReader r; private VirtualDisplay vd; private volatile int edge=720,fps=15,quality=60; private long last; private int realW,realH; private long lastHash=Long.MIN_VALUE; private int sameFrames=0;
 public FrameStreamer(Context c,MediaProjection p,Sink s){this.c=c;this.p=p;this.sink=s;}
 public void start(){t=new HandlerThread("LANRemoteCapture");t.start();h=new Handler(t.getLooper());h.post(()->configure());}
 public void config(int e,int f,int q){edge=Math.max(320,Math.min(1280,e));fps=Math.max(1,Math.min(60,f));quality=Math.max(30,Math.min(90,q));if(h!=null)h.post(()->configure());}
 private Point size(){Point q=new Point();((WindowManager)c.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay().getRealSize(q);return q;}
 private void configure(){Point s=size();realW=s.x;realH=s.y;float k=Math.min(1f,edge/(float)Math.max(s.x,s.y));int w=Math.max(2,((int)(s.x*k))&~1),hh=Math.max(2,((int)(s.y*k))&~1);ImageReader nr=ImageReader.newInstance(w,hh,PixelFormat.RGBA_8888,2);nr.setOnImageAvailableListener(x->image(x,w,hh),h);ImageReader old=r;r=nr;int d=c.getResources().getDisplayMetrics().densityDpi;if(vd==null)vd=p.createVirtualDisplay("LANRemote",w,hh,d,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,r.getSurface(),null,h);else{vd.resize(w,hh,d);vd.setSurface(r.getSurface());}if(old!=null)old.close();lastHash=Long.MIN_VALUE;sameFrames=0;}
 private long quickHash(ByteBuffer b,int rowStride,int pixelStride,int w,int hh){long x=1469598103934665603L;int sy=Math.max(1,hh/18),sx=Math.max(1,w/24);for(int y=0;y<hh;y+=sy)for(int xx=0;xx<w;xx+=sx){int i=y*rowStride+xx*pixelStride;if(i+2<b.limit()){x^=(b.get(i)&255)|((b.get(i+1)&255)<<8)|((b.get(i+2)&255)<<16);x*=1099511628211L;}}return x;}
 private void image(ImageReader ir,int w,int hh){Image im=null;try{im=ir.acquireLatestImage();if(im==null||ir!=r)return;Point now=size();if(now.x!=realW||now.y!=realH){h.post(()->configure());return;}long n=SystemClock.elapsedRealtime();if(n-last<1000/Math.max(1,fps))return;Image.Plane pl=im.getPlanes()[0];ByteBuffer buf=pl.getBuffer();long hash=quickHash(buf,pl.getRowStride(),pl.getPixelStride(),w,hh);if(hash==lastHash){sameFrames++;if(sameFrames<Math.max(2,fps/5))return;sameFrames=0;}else{sameFrames=0;lastHash=hash;}last=n;int ps=pl.getPixelStride(),rs=pl.getRowStride(),pw=w+(rs-ps*w)/ps;buf.rewind();Bitmap pad=Bitmap.createBitmap(pw,hh,Bitmap.Config.ARGB_8888);pad.copyPixelsFromBuffer(buf);Bitmap b=Bitmap.createBitmap(pad,0,0,w,hh);ByteArrayOutputStream o=new ByteArrayOutputStream(Math.max(16384,w*hh/8));b.compress(Bitmap.CompressFormat.JPEG,quality,o);sink.frame(o.toByteArray(),w,hh);b.recycle();if(b!=pad)pad.recycle();}catch(Throwable x){x.printStackTrace();}finally{if(im!=null)im.close();}}
 public void stop(){try{if(vd!=null)vd.release();}catch(Throwable x){}try{if(r!=null)r.close();}catch(Throwable x){}if(t!=null)t.quitSafely();}
}
