package cl.will.lanremote;
import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.atomic.AtomicReference;
public class LanServer implements FrameStreamer.Sink {
 private final int port; private ServerSocket ss; private volatile boolean run; private Thread accept; private final AtomicReference<Client> current=new AtomicReference<>(); private volatile FrameStreamer streamer;
 public LanServer(int port){this.port=port;} public void setStreamer(FrameStreamer s){streamer=s;} public void start(){run=true;accept=new Thread(()->{try{ss=new ServerSocket(port);while(run){Socket s=ss.accept();s.setTcpNoDelay(true);Client c=new Client(s);Client old=current.getAndSet(c);if(old!=null)old.close();new Thread(c,"LANRemoteClient").start();}}catch(Exception e){if(run)e.printStackTrace();}},"LANRemoteAccept");accept.start();}
 public void stop(){run=false;try{if(ss!=null)ss.close();}catch(Exception e){}Client c=current.getAndSet(null);if(c!=null)c.close();}
 public void frame(byte[] jpg,int w,int h){Client c=current.get();if(c!=null&&c.video)c.offer(jpg,w,h);}
 class Client implements Runnable {Socket s;DataInputStream in;DataOutputStream out;final AtomicReference<Frame> latest=new AtomicReference<>();volatile boolean alive=true,video=false;Client(Socket x)throws Exception{s=x;in=new DataInputStream(new BufferedInputStream(x.getInputStream()));out=new DataOutputStream(new BufferedOutputStream(x.getOutputStream()));}
  void offer(byte[] b,int w,int h){latest.set(new Frame(b,w,h));} void close(){alive=false;RemoteAccessibilityService.cursorVisible(false);try{s.close();}catch(Exception e){}}
  public void run(){Thread tx=new Thread(()->sendLoop(),"LANRemoteVideo");tx.start();try{String line;BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));while(alive&&(line=br.readLine())!=null)command(line);}catch(Exception e){}finally{close();}}
  void command(String q){try{String[] a=q.split(" ",5);if(a[0].equals("VIDEO")&&a.length>=3){video=true;int e=Integer.parseInt(a[1]),f=Integer.parseInt(a[2]),quality=a.length>=4?Integer.parseInt(a[3]):60;if(streamer!=null)streamer.config(e,f,quality);}else if(a[0].equals("INPUTONLY")){video=false;latest.set(null);}else if(a[0].equals("TAP"))RemoteAccessibilityService.tapNormalized(Integer.parseInt(a[1]),Integer.parseInt(a[2]));else if(a[0].equals("SWIPE")){String[] z=q.split(" ");RemoteAccessibilityService.swipeNormalized(Integer.parseInt(z[1]),Integer.parseInt(z[2]),Integer.parseInt(z[3]),Integer.parseInt(z[4]),Integer.parseInt(z[5]));}else if(a[0].equals("MOUSE"))RemoteAccessibilityService.moveCursor(Integer.parseInt(a[1]),Integer.parseInt(a[2]));else if(a[0].equals("CLICK"))RemoteAccessibilityService.clickCursor();else if(a[0].equals("SCROLL"))RemoteAccessibilityService.scrollCursor(Integer.parseInt(a[1]));else if(a[0].equals("CURSOR"))RemoteAccessibilityService.cursorVisible(a.length>1&&"SHOW".equalsIgnoreCase(a[1]));else if(a[0].equals("GLOBAL"))RemoteAccessibilityService.global(a[1]);else if(a[0].equals("TEXT")&&a.length>=4){int p1=q.indexOf(' '),p2=q.indexOf(' ',p1+1),p3=q.indexOf(' ',p2+1);if(p3>=0)RemoteAccessibilityService.commitRemoteText(q.substring(p3+1));}else if(a[0].equals("KEY"))RemoteAccessibilityService.remoteKey(a[1]);}catch(Exception e){}}
  void sendLoop(){try{while(alive){Frame f=latest.getAndSet(null);if(f==null||!video){Thread.sleep(2);continue;}synchronized(out){out.writeInt(Protocol.MAGIC);out.writeInt(f.w);out.writeInt(f.h);out.writeInt(f.b.length);out.write(f.b);out.flush();}}}catch(Exception e){close();}}
 }
 static class Frame{byte[]b;int w,h;Frame(byte[]b,int w,int h){this.b=b;this.w=w;this.h=h;}}
}
