package cl.will.lanremote;
import android.app.*;import android.content.*;import android.graphics.Color;import android.media.projection.*;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.net.*;import java.util.*;
public class MainActivity extends Activity {static final int CAP=9;TextView st;EditText portBox;
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(36,42,36,30);r.setBackgroundColor(Color.rgb(245,240,232));TextView t=new TextView(this);t.setText("LAN Remote v0.6");t.setTextSize(30);r.addView(t);LinearLayout pr=new LinearLayout(this);pr.setOrientation(LinearLayout.HORIZONTAL);TextView pl=new TextView(this);pl.setText("Port: ");pl.setTextSize(17);pr.addView(pl);portBox=new EditText(this);portBox.setInputType(InputType.TYPE_CLASS_NUMBER);portBox.setText(String.valueOf(getPreferences(0).getInt("port",Protocol.PORT)));portBox.setEms(6);pr.addView(portBox);r.addView(pr);st=new TextView(this);st.setText(info());st.setTextSize(16);st.setPadding(0,15,0,20);r.addView(st);r.addView(btn("1. Enable Accessibility",v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))));r.addView(btn("2. Enable LAN Remote Keyboard",v->startActivity(new Intent(Settings.ACTION_INPUT_METHOD_SETTINGS))));r.addView(btn("3. Choose active keyboard",v->{InputMethodManager im=(InputMethodManager)getSystemService(INPUT_METHOD_SERVICE);im.showInputMethodPicker();}));r.addView(btn("Start Input Only",v->startInputOnly()));r.addView(btn("Start Screen Mirroring",v->startActivityForResult(((MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE)).createScreenCaptureIntent(),CAP)));r.addView(btn("Stop",v->stopService(new Intent(this,LanRemoteService.class))));setContentView(r);}
 protected void onResume(){super.onResume();if(st!=null)st.setText(info());}
 int port(){try{int p=Integer.parseInt(portBox.getText().toString());if(p<1024||p>65535)throw new Exception();getPreferences(0).edit().putInt("port",p).apply();return p;}catch(Exception e){portBox.setText(String.valueOf(Protocol.PORT));return Protocol.PORT;}}
 String info(){String def=Settings.Secure.getString(getContentResolver(),Settings.Secure.DEFAULT_INPUT_METHOD);boolean ime=def!=null&&def.contains(getPackageName());int p=portBox==null?getPreferences(0).getInt("port",Protocol.PORT):port();return "Android → Windows 7 over Wi-Fi LAN\n\nPC connects to: "+ip()+":"+p+"\n\nLAN Remote Keyboard active: "+(ime?"YES":"NO")+"\nEnable Accessibility too for mouse/touch control.";}
 Intent serviceIntent(){Intent x=new Intent(this,LanRemoteService.class);x.putExtra(LanRemoteService.EXTRA_PORT,port());return x;}
 void startInputOnly(){Intent x=serviceIntent();if(Build.VERSION.SDK_INT>=26)startForegroundService(x);else startService(x);st.setText("Input Only server active at "+ip()+":"+port()+"\nAndroid screen stays in use.");}
 Button btn(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setOnClickListener(l);return b;}
 protected void onActivityResult(int q,int c,Intent d){super.onActivityResult(q,c,d);if(q==CAP&&c==RESULT_OK){Intent x=serviceIntent();x.putExtra(LanRemoteService.EXTRA_CODE,c);x.putExtra(LanRemoteService.EXTRA_DATA,d);if(Build.VERSION.SDK_INT>=26)startForegroundService(x);else startService(x);st.setText("Screen Mirroring server active at "+ip()+":"+port());}}
 String ip(){try{Enumeration<NetworkInterface> ns=NetworkInterface.getNetworkInterfaces();while(ns.hasMoreElements()){Enumeration<InetAddress> as=ns.nextElement().getInetAddresses();while(as.hasMoreElements()){InetAddress a=as.nextElement();if(!a.isLoopbackAddress()&&a instanceof Inet4Address)return a.getHostAddress();}}}catch(Exception e){}return "check Wi-Fi IP";}}
