plugins { id 'com.android.application' }
android {
 namespace 'cl.will.lanremote'; compileSdk 35
 defaultConfig { applicationId 'cl.will.lanremote'; minSdk 26; targetSdk 35; versionCode 3; versionName '0.3.0' }
 buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
